version: '3.8'
services:
  s1:
    image: 192.168.122.209:5000/images1
    build:
      context: .
      dockerfile: ./Dockerfile_s1
    depends_on:
      - "s2"
      - "s4"
      - "s4b"
      - "s5"
    ports:
      - 443:443
  s2:
    image: 192.168.122.209:5000/images2
    build:
      context: .
      dockerfile: ./Dockerfile_s2
    depends_on:
      - "s6"
  s4:
    image: 192.168.122.209:5000/images4
    build:
      context: .
      dockerfile: ./Dockerfile_s4
    depends_on:
      - "s6"
    volumes:
      - ./uploads:/var/www/html/uploads
    links:
      - "s6:db.extagram.edt"
  s4b:
    image: 192.168.122.209:5000/images4b
    build:
      context: .
      dockerfile: ./Dockerfile_s4b
    volumes:
      - ./uploads:/var/www/html
  s5:
    image: 192.168.122.209:5000/images5
    build:
      context: .
      dockerfile: ./Dockerfile_s5
  s6:
    image: 192.168.122.209:5000/images6
    build:
      context: .
      dockerfile: ./Dockerfile_s6
    environment:
      MYSQL_DATABASE: extagram_db
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: extagram_admin
      MYSQL_PASSWORD: pass123
    volumes:
      - ./dbdata:/var/lib/mysql
