version: '3.3'
services:
  proxy:
    build:
      context: .
      dockerfile: proxy/Dockerfile
    depends_on:
      - home
      - upload
      - storage
      - static
    ports:
      - 443:443
    configs:
      - source: proxy_nginx_conf
        target: /etc/nginx/conf.d/default.conf 
    secrets:
      - site.key
      - site.pem
  home:
    build:
      context: .
      dockerfile: home/Dockerfile
    depends_on:
      - database
    volumes:
      - ./app/extagram.php:/var/www/html/extagram.php
  upload:
    build:
      context: .
      dockerfile: upload/Dockerfile
    depends_on:
      - database
    volumes:
      - images:/var/www/html/upload/images
      - ./app/upload.php:/var/www/html/upload/upload.php
      - ./app/reset.php:/var/www/html/upload/reset.php
  storage:
    build:
      context: .
      dockerfile: storage/Dockerfile
    volumes:
      - images:/var/www/html/storage/
    configs:
      - source: storage_nginx_conf
        target: /etc/nginx/conf.d/default.conf 
  static:
    build:
      context: .
      dockerfile: static/Dockerfile
    volumes:
      - ./app/static:/var/www/html/static/
    configs:
      - source: static_nginx_conf
        target: /etc/nginx/conf.d/default.conf 
  database:
    build:
      context: .
      dockerfile: database/Dockerfile
    environment:
      MYSQL_DATABASE: extagram_db
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: extagram_admin
      MYSQL_PASSWORD: pass123
    volumes:
      - dbdata:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  dbdata:
  images:

configs:
  proxy_nginx_conf:
    file: ./proxy/nginx.conf
  storage_nginx_conf:
    file: ./storage/nginx.conf
  static_nginx_conf:
    file: ./static/nginx.conf
secrets:
  site.key:
    file: ./proxy/site.key
  site.pem:
    file: ./proxy/site.pem
